---
title: "Homework 1"
author: "Ruthie Montella"
format:
  html:
    toc: true
    toc-location: left
    self-contained: true
jupyter: python3
---

Professional wrestling, while not everyone's cup of tea, is big business. What started as a carnival act has turned into a global entertainment industry. Netflix recently started showing Monday Night Raw, a program from the biggest North American wrestling company, WWE -- this deal is reportedly worth \$5 billion. Like any large entity, WWE is not without competition, drama, and scandal. 

## General Tips

This is very much a step-by-step process. Don't go crazy trying to get everything done with as few lines as possible. Read the documentation for the AlphaVantage api! Carefully explore the pages from cagematch. There isn't a need to get too fancy with anything here -- just go with simple function and all should be good. Don't print comments, but use normal text for explanations.

## Step 1

In the `calls` folder, you'll find 4 text files -- these are transcripts from quarterly earnings calls. Read those files in (glob.glob will be very helpful here), with appropriate column names for ticker, quarter, and year columns; this should be done within a single function. Perform any data cleaning that you find necessary. 

```{python}
import glob as glob
import pandas as pd
import re


def read_calls(path_to_folder): 
  file_paths = glob.glob(path_to_folder)
  data = []

  for file_path in file_paths: 
    file_name = file_path.split("/")[-1]
    match = re.match(r"([a-z]+)_(q\d)_(\d{4})\.txt", file_name) 
    if match:
      ticker = match.group(1)
      quarter = match.group(2)
      year = match.group(3)
    else: 
      print("Skipping file {file_name} - invalid format.")
      continue # continue on to the next file name and check that one
    
    with open(file_path, "r", encoding="utf-8") as f: 
            content = f.read()  # reading content of the file 
    
    # split the text so every line has its own line/not all combined:
    content_lines = content.split('\n')
    for line in content_lines:
      data.append([ticker, quarter, year, line.strip()])

    #data.append([ticker, quarter, year, content]) # add all the elements into the empty list 
  print(f"Number of rows collected: {len(data)}")
  if len(data) > 0:
    print(f"First row of data: {data[0]}")
    
  df = pd.DataFrame(data, columns=["ticker", "quarter", "year", "content"])
  return df


#path_to_folder = "/Users/ruthiemontella/Desktop/uda_notes/assignment_1/calls/*.txt"

read_calls("/Users/ruthiemontella/Desktop/uda_notes/assignment_1/calls/*.txt")

#glob.glob("/Users/ruthiemontella/Desktop/uda_notes/assignment_1/calls/*.txt")
```

## Step 2

Use the AlphaVantage api to get daily stock prices for WWE and related tickers for the last 5 years -- pay attention to your data. You cannot use any AlphaVantage packages (i.e., you can only use requests to grab the data). Tell me about the general trend that you are seeing. I don't care which viz package you use, but plotly is solid and plotnine is good for ggplot2 users.

```{python}
import requests 


av_k = "LHZYEPZLB5K2R01C"

av_symbol = "WWE"

av_link = "https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY&symbol={}&apikey={}".format(
  av_symbol, av_k)

av_request = requests.get(av_link)

av_json = av_request.json()

series_data = av_json['Weekly Time Series']

meta_data = av_json['Meta Data']

av_data = pd.DataFrame.from_dict(series_data, orient='index')

av_data['symbol'] = meta_data['2. Symbol']

av_data.reset_index(inplace = True)

av_data = av_data.rename(columns = {'index':'date'})

```

## Step 3

Just like every other nerdy hobby, professional wrestling draws dedicated fans. Wrestling fans often go to cagematch.net to leave reviews for matches, shows, and wrestlers. The following link contains the top 100 matches on cagematch: https://www.cagematch.net/?id=111&view=statistics

* What is the correlation between WON ratings and cagematch ratings?

** Which wrestler has the most matches in the top 100?

*** Which promotion has the most matches in the top 100? 

**** What is each promotion's average WON rating?

***** Select any single match and get the comments and ratings for that match into a data frame.

```{python}
from bs4 import BeautifulSoup

```

## Step 4

You can't have matches without wrestlers. The following link contains the top 100 wrestlers, according to cagematch: https://www.cagematch.net/?id=2&view=statistics

*** Of the top 100, who has wrestled the most matches?

***** Of the top 100, which wrestler has the best win/loss?

```{python}

```

## Step 5

With all of this work out of the way, we can start getting down to strategy.

First, what talent should WWE pursue? Advise carefully.

Second, reconcile what you found in steps 3 and 4 with Netflix's relationship with WWE. Use the data from the following page to help make your case: https://wrestlenomics.com/tv-ratings/

Third, do you have any further recommendations for WWE?